// packages/grammar-app/src/components/react-wrapper/UDIToolkitProvider.tsx
import * as React from 'react';
import type { UDIPalette } from '../Palette';
import { loadDataPackage } from './loadDataPackage';
import type { SourceSpec, LoadDataPackageOptions } from '../loadDataPackage';

export type DataPackageLoadPhase = 'idle' | 'loading' | 'ready' | 'error';

export interface DataPackageStatus {
  phase: DataPackageLoadPhase;
  /** Most recent error from any source's load. Cleared on a fresh attempt. */
  error: string | null;
}

export interface DataPackageConfig extends LoadDataPackageOptions {
  /** Sources to fetch + cache. */
  sources: SourceSpec[];
}

export interface UDIToolkitContextValue {
  palette: UDIPalette | undefined;
  status: DataPackageStatus;
}

/**
 * Internal context shared by `UDIToolkitProvider` and the hook surface. The
 * default is the no-provider state — calls to `usePalette` outside a provider
 * read `undefined` (descendants then fall back to `DEFAULT_PALETTE` via the
 * usual per-channel resolution in VegaLite.vue / table cell renderers).
 */
export const UDIToolkitContext = React.createContext<UDIToolkitContextValue>({
  palette: undefined,
  status: { phase: 'idle', error: null },
});

export interface UDIToolkitProviderProps {
  /**
   * Default palette inherited by every nested `<UDIVis>`. A per-instance
   * `palette` prop on the chart still wins — the context is a *fallback*,
   * not an override.
   */
  palette?: UDIPalette;
  /**
   * Optional data-package descriptor. When supplied, the provider calls
   * `loadDataPackage(sources, options)` on mount (and again any time the
   * `sources` array's URL list changes), seeds the shared DataSourcesStore,
   * and tracks load progress in `useDataPackageStatus()`. Consumers driving
   * the load themselves can omit this and the provider stays palette-only.
   */
  dataPackage?: DataPackageConfig;
  children?: React.ReactNode;
}

/** Identity-stable join of source URLs — drives the load-effect's deps. */
function sourceFingerprint(sources: SourceSpec[] | undefined): string {
  if (!sources || sources.length === 0) return '';
  return sources.map((s) => `${s.name}|${s.url}`).join('\n');
}

/**
 * Root-level Provider for the udi-toolkit. Holds the consumer palette and,
 * if `dataPackage` is supplied, auto-loads it via the shared Pinia
 * DataSourcesStore. Place once at the root of your app; nested `<UDIVis>`
 * instances inherit the palette without per-instance threading and
 * descendant hooks (`useSelections`, `useQueryData`, `useDataPackageStatus`,
 * `useClearAllSelections`) can subscribe to the data layer without each
 * consumer rebuilding the same subscribe/pump scaffold.
 */
export function UDIToolkitProvider({
  palette,
  dataPackage,
  children,
}: UDIToolkitProviderProps): React.ReactElement {
  const [status, setStatus] = React.useState<DataPackageStatus>({
    phase: 'idle',
    error: null,
  });

  // Use a fingerprint to depend on the sources' contents rather than their
  // array identity — common for inline object-literal props.
  const fingerprint = sourceFingerprint(dataPackage?.sources);

  // Stash the latest callbacks in a ref so a callback prop swap doesn't
  // re-trigger the load effect (only sources should).
  const cfgRef = React.useRef<DataPackageConfig | undefined>(dataPackage);
  cfgRef.current = dataPackage;

  React.useEffect(() => {
    const cfg = cfgRef.current;
    if (!cfg || cfg.sources.length === 0) return;
    let cancelled = false;
    setStatus({ phase: 'loading', error: null });
    let observedError: string | null = null;
    void loadDataPackage(cfg.sources, {
      fetchOptions: cfg.fetchOptions,
      onEntityDomains: (entity, domains) => {
        if (cancelled) return;
        cfgRef.current?.onEntityDomains?.(entity, domains);
      },
      onError: (entity, message) => {
        if (cancelled) return;
        observedError = message;
        cfgRef.current?.onError?.(entity, message);
      },
    })
      .then(() => {
        if (cancelled) return;
        setStatus(
          observedError === null
            ? { phase: 'ready', error: null }
            : { phase: 'error', error: observedError },
        );
      })
      .catch((e) => {
        if (cancelled) return;
        const msg = e instanceof Error ? e.message : String(e);
        setStatus({ phase: 'error', error: msg });
      });
    return () => {
      cancelled = true;
    };
  }, [fingerprint]);

  const value = React.useMemo<UDIToolkitContextValue>(
    () => ({ palette, status }),
    [palette, status],
  );

  return <UDIToolkitContext.Provider value={value}>{children}</UDIToolkitContext.Provider>;
}

// packages/grammar/UDIToolkitProvider.vue
<script setup lang="ts">
import { provide, toRef, watch, onBeforeUnmount } from 'vue';
import { getActivePinia } from 'pinia';
import { UDI_PALETTE_KEY } from './paletteInjectKey';
import {
  loadDataPackage,
  type SourceSpec,
  type LoadDataPackageOptions,
} from './loadDataPackage';
import type { UDIPalette } from './Palette';

interface DataPackageConfig extends LoadDataPackageOptions {
  /** Sources to fetch + cache. */
  sources: SourceSpec[];
}

interface UDIToolkitProviderProps {
  /**
   * Default palette inherited by every nested `UDIVis` / `TableComponent`.
   * A descendant's own `palette` prop still wins.
   */
  palette?: UDIPalette;
  /**
   * Optional data-package descriptor — when provided the provider will fetch
   * the listed CSVs once on mount (and again any time `sources` identity
   * changes), seed the shared DataSourcesStore, and stream per-field domains
   * back through `onEntityDomains`. Consumers that already drive the load
   * themselves can omit this and the provider stays palette-only.
   */
  dataPackage?: DataPackageConfig;
}

const props = defineProps<UDIToolkitProviderProps>();

// Provide a Ref (rather than the value) so descendants see prop swaps —
// e.g. a host that toggles light/dark palette at runtime.
provide(UDI_PALETTE_KEY, toRef(props, 'palette'));

// Track in-flight loads so a fast prop swap doesn't apply a stale result.
// We don't currently have a cancel hook on loadDataPackage; this token gate
// is the next best thing.
let loadToken = 0;

watch(
  () => props.dataPackage,
  (cfg) => {
    if (!cfg) return;
    const pinia = getActivePinia();
    if (!pinia) {
      console.warn(
        '[UDIToolkitProvider] No active Pinia — `dataPackage` was supplied ' +
          'but loadDataPackage requires Pinia to be installed. Did you forget ' +
          '`app.use(UDIToolkit)` (or `app.use(createPinia())`)?',
      );
      return;
    }
    const token = ++loadToken;
    const { sources, ...options } = cfg;
    loadDataPackage(pinia, sources, {
      ...options,
      onEntityDomains: (entity, domains) => {
        if (token !== loadToken) return;
        options.onEntityDomains?.(entity, domains);
      },
      onError: (entity, message) => {
        if (token !== loadToken) return;
        options.onError?.(entity, message);
      },
    }).catch((e) => {
      if (token !== loadToken) return;
      const msg = e instanceof Error ? e.message : String(e);
      options.onError?.('', msg);
    });
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  // Invalidate any pending callbacks from in-flight loads.
  loadToken++;
});
</script>

<template>
  <slot />
</template>
